### ISSUE TITLE
emscripten: Unable to successfully compile on versions EMSDK 3.1.56 and later

### ISSUE THREAD

**Issue by xrui94** [eliemichel/WebGPU-Cpp#16]
Compilation can be successful on version 3.1.47, but it does not seem to support OffscreenCanvas. According to this [answer](https://github.com/emscripten-core/emscripten/issues/19645#issuecomment-2073593691), versions 3.1.56 and later support OffscreenCanvas, but compilation cannot be successful on versions 3.1.56 and later. The compilation error infor is:

![image](https://github.com/eliemichel/WebGPU-Cpp/assets/29156275/00a1411c-757f-4879-9889-f21b6587749e)

**Comment by eliemichel** [comment]
Hello, I try to make sure there is always a `[emscripten-git-tag.txt](https://github.com/eliemichel/WebGPU-Cpp/blob/main/emscripten/emscripten-git-tag.txt)` file somewhere around webgpu.h/webgpu.hpp headers, as it is still continuously changing. Until 2 days ago, the webgpu.hpp provided here was limited to an older emscripten, but **it now supports emscripten 3.1.61**!

Note that you may at any time generate your own header, either using the `generator.py` (see [the end of the README](https://github.com/eliemichel/WebGPU-Cpp?tab=readme-ov-file#update-all-generated-examples)) or -- even simpler -- through the Web service: https://eliemichel.github.io/WebGPU-Cpp

**Comment by xrui94** [comment]
> Hello, I try to make sure there is always a [`emscripten-git-tag.txt`](https://github.com/eliemichel/WebGPU-Cpp/blob/main/emscripten/emscripten-git-tag.txt) file somewhere around webgpu.h/webgpu.hpp headers, as it is still continuously changing. Until 2 days ago, the webgpu.hpp provided here was limited to an older emscripten, but **it now supports emscripten 3.1.61**!
> 
> Note that you may at any time generate your own header, either using the `generator.py` (see [the end of the README](https://github.com/eliemichel/WebGPU-Cpp?tab=readme-ov-file#update-all-generated-examples)) or -- even simpler -- through the Web service: https://eliemichel.github.io/WebGPU-Cpp

Thanks, I got it!

**Comment by xrui94** [comment]
> Hello, I try to make sure there is always a [`emscripten-git-tag.txt`](https://github.com/eliemichel/WebGPU-Cpp/blob/main/emscripten/emscripten-git-tag.txt) file somewhere around webgpu.h/webgpu.hpp headers, as it is still continuously changing. Until 2 days ago, the webgpu.hpp provided here was limited to an older emscripten, but **it now supports emscripten 3.1.61**!
> 
> Note that you may at any time generate your own header, either using the `generator.py` (see [the end of the README](https://github.com/eliemichel/WebGPU-Cpp?tab=readme-ov-file#update-all-generated-examples)) or -- even simpler -- through the Web service: https://eliemichel.github.io/WebGPU-Cpp

Hello, Successfully compiled on emsdk-v3.1.56 and 3.1.61, but encountered the following error during runtime:
![image](https://github.com/eliemichel/WebGPU-Cpp/assets/29156275/37286806-eca6-459f-96a7-7fa83f0bcea9)

Meanwhile, I found the following relevant code in the webgpu.cpp file:
![image](https://github.com/eliemichel/WebGPU-Cpp/assets/29156275/3686a2b1-7aed-40eb-a18c-df83ac175b5e)

**Comment by eliemichel** [comment]
Yes, this is mentionned at the end of the new [Hello WebGPU](https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html#building-for-the-web) chapter: I don't know why they do that but emscripten refuses a non-null pointer so I add a `#ifdef` there.
